# Workflow to build and deploy a React app with Vite to GitHub Pages
name: Deploy React App with GitHub Pages

on:
  # Ejecutar en el branch principal
  push:
    branches: ["main"]

  # Permite ejecutar el flujo de trabajo manualmente desde la pestaña Actions
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build the project
        run: npm run build

      - name: Upload build to GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./dist # Cambia a tu carpeta de salida Vite (dist)

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4